#include "graphics.h"
#include "structs.h"
const char* entries_0[] = { "Xbox","Xbox One","Playstation 2","Genesis","Dreamcast","Switch","Wii U","SNES","N64","PC","TV", };
const struct sequence sequence_0 = { "dummyname", 11, entries_0};
const struct menu menu_0 = {"Main Menu","placeholder",&placeholder_bmp,"Main Menu",sequence_0};
const char* entries_1[] = {  };
const struct sequence sequence_1 = { "dummyname", 0, entries_1};
const struct menu menu_1 = {"Xbox","xbox",&xbox_bmp,"Original Xbox",sequence_1};
const char* entries_2[] = {  };
const struct sequence sequence_2 = { "dummyname", 0, entries_2};
const struct menu menu_2 = {"Xbox One","xboxone",&xboxone_bmp,"Xbox One",sequence_2};
const char* entries_3[] = { "RebootPS2", };
const struct sequence sequence_3 = { "dummyname", 1, entries_3};
const struct menu menu_3 = {"Playstation 2","ps2",&ps2_bmp,"Playstation 2",sequence_3};
const char* entries_4[] = { "RebootGenesis", };
const struct sequence sequence_4 = { "dummyname", 1, entries_4};
const struct menu menu_4 = {"Genesis","sega",&sega_bmp,"Genesis",sequence_4};
const char* entries_5[] = { "RebootDreamcast", };
const struct sequence sequence_5 = { "dummyname", 1, entries_5};
const struct menu menu_5 = {"Dreamcast","dreamcast",&dreamcast_bmp,"Dreamcast",sequence_5};
const char* entries_6[] = {  };
const struct sequence sequence_6 = { "dummyname", 0, entries_6};
const struct menu menu_6 = {"Switch","switch",&switch_bmp,"Switch",sequence_6};
const char* entries_7[] = {  };
const struct sequence sequence_7 = { "dummyname", 0, entries_7};
const struct menu menu_7 = {"Wii U","wiiu",&wiiu_bmp,"Wii U/Wii/Gamecube",sequence_7};
const char* entries_8[] = { "RebootSNES", };
const struct sequence sequence_8 = { "dummyname", 1, entries_8};
const struct menu menu_8 = {"SNES","snes",&snes_bmp,"Super Nintendo Entertainment System",sequence_8};
const char* entries_9[] = { "RebootN64", };
const struct sequence sequence_9 = { "dummyname", 1, entries_9};
const struct menu menu_9 = {"N64","n64",&n64_bmp,"Nintendo 64",sequence_9};
const char* entries_10[] = {  };
const struct sequence sequence_10 = { "dummyname", 0, entries_10};
const struct menu menu_10 = {"PC","placeholder",&placeholder_bmp,"PC",sequence_10};
const char* entries_11[] = { "TV Power Toggle","TV Input Up","TV Input Down","TV Input Left","TV Input Right","TV Input Enter","TV Menu","TV Input AppMenu","TV Input Back","TV Input Exit","Volume Up","Volume Down","Volume Mute","Refresh Display","Control Lights", };
const struct sequence sequence_11 = { "dummyname", 15, entries_11};
const struct menu menu_11 = {"TV","placeholder",&placeholder_bmp,"LG C1",sequence_11};
const char* entries_12[] = { "Livingroom Lights","Kitchen Lights","Master Bedroom Lights","Outside Lights","Lights Off","Lights On","Lights Red Up","Lights Red Down","Lights Green Up","Lights Green Down","Lights Blue Up","Lights Blue Down","Lights White Up","Lights White Down","Lights Brightness Up","Lights Brightness Down","Control TV", };
const struct sequence sequence_12 = { "dummyname", 17, entries_12};
const struct menu menu_12 = {"Lights","placeholder",&placeholder_bmp,"Toggle Lights",sequence_12};
struct menu menus[] = { menu_0,menu_1,menu_2,menu_3,menu_4,menu_5,menu_6,menu_7,menu_8,menu_9,menu_10,menu_11,menu_12, };
uint32_t numMenus = 13;
const struct action_haservice action_data_member_0 = { "media_player.volume_up", "", "{\"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_0 = {.haservice = action_data_member_0 };
const struct action action_0 = { action_data_0, ACTION_HASERVICE };
const struct action actions_0[] = { action_0, };
const struct button button_0 = { "Volume Up", "placeholder", &placeholder_bmp, "Volume Up", 1, actions_0 };
const struct action_haservice action_data_member_1 = { "media_player.volume_down", "", "{\"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_1 = {.haservice = action_data_member_1 };
const struct action action_1 = { action_data_1, ACTION_HASERVICE };
const struct action actions_1[] = { action_1, };
const struct button button_1 = { "Volume Down", "placeholder", &placeholder_bmp, "Volume Down", 1, actions_1 };
const struct action_haservice action_data_member_2 = { "webostv.button", "", "{\"button\": \"MUTE\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_2 = {.haservice = action_data_member_2 };
const struct action action_2 = { action_data_2, ACTION_HASERVICE };
const struct action actions_2[] = { action_2, };
const struct button button_2 = { "Volume Mute", "placeholder", &placeholder_bmp, "Volume Mute", 1, actions_2 };
const struct action_jump action_data_member_3 = { "Main Menu" };
const union actionData action_data_3 = {.jump = action_data_member_3 };
const struct action action_3 = { action_data_3, ACTION_JUMP };
const struct action actions_3[] = { action_3, };
const struct button button_3 = { "Main Menu", "placeholder", &placeholder_bmp, "Main Menu", 1, actions_3 };
const struct action_haservice action_data_member_4 = { "script.rebootps2", "", "" };
const union actionData action_data_4 = {.haservice = action_data_member_4 };
const struct action action_4 = { action_data_4, ACTION_HASERVICE };
const struct action actions_4[] = { action_4, };
const struct button button_4 = { "RebootPS2", "placeholder", &placeholder_bmp, "Reboot Playstation 2", 1, actions_4 };
const struct action_haservice action_data_member_5 = { "script.rebootgenesis", "", "" };
const union actionData action_data_5 = {.haservice = action_data_member_5 };
const struct action action_5 = { action_data_5, ACTION_HASERVICE };
const struct action actions_5[] = { action_5, };
const struct button button_5 = { "RebootGenesis", "placeholder", &placeholder_bmp, "Reboot Genesis", 1, actions_5 };
const struct action_haservice action_data_member_6 = { "script.rebootsnes", "", "" };
const union actionData action_data_6 = {.haservice = action_data_member_6 };
const struct action action_6 = { action_data_6, ACTION_HASERVICE };
const struct action actions_6[] = { action_6, };
const struct button button_6 = { "RebootSNES", "placeholder", &placeholder_bmp, "Reboot Super Nintendo Entertainment System", 1, actions_6 };
const struct action_haservice action_data_member_7 = { "script.rebootn64", "", "" };
const union actionData action_data_7 = {.haservice = action_data_member_7 };
const struct action action_7 = { action_data_7, ACTION_HASERVICE };
const struct action actions_7[] = { action_7, };
const struct button button_7 = { "RebootN64", "placeholder", &placeholder_bmp, "Reboot Nintendo 64", 1, actions_7 };
const struct action_haservice action_data_member_8 = { "script.rebootps2", "", "" };
const union actionData action_data_8 = {.haservice = action_data_member_8 };
const struct action action_8 = { action_data_8, ACTION_HASERVICE };
const struct action actions_8[] = { action_8, };
const struct button button_8 = { "RebootDreamcast", "placeholder", &placeholder_bmp, "Reboot Dreamcast", 1, actions_8 };
const struct action_haservice action_data_member_9 = { "webostv.button", "", "{\"button\": \"UP\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_9 = {.haservice = action_data_member_9 };
const struct action action_9 = { action_data_9, ACTION_HASERVICE };
const struct action actions_9[] = { action_9, };
const struct button button_9 = { "TV Input Up", "placeholder", &placeholder_bmp, "Up", 1, actions_9 };
const struct action_haservice action_data_member_10 = { "webostv.button", "", "{\"button\": \"DOWN\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_10 = {.haservice = action_data_member_10 };
const struct action action_10 = { action_data_10, ACTION_HASERVICE };
const struct action actions_10[] = { action_10, };
const struct button button_10 = { "TV Input Down", "placeholder", &placeholder_bmp, "Down", 1, actions_10 };
const struct action_haservice action_data_member_11 = { "webostv.button", "", "{\"button\": \"LEFT\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_11 = {.haservice = action_data_member_11 };
const struct action action_11 = { action_data_11, ACTION_HASERVICE };
const struct action actions_11[] = { action_11, };
const struct button button_11 = { "TV Input Left", "placeholder", &placeholder_bmp, "Left", 1, actions_11 };
const struct action_haservice action_data_member_12 = { "webostv.button", "", "{\"button\": \"RIGHT\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_12 = {.haservice = action_data_member_12 };
const struct action action_12 = { action_data_12, ACTION_HASERVICE };
const struct action actions_12[] = { action_12, };
const struct button button_12 = { "TV Input Right", "placeholder", &placeholder_bmp, "Right", 1, actions_12 };
const struct action_haservice action_data_member_13 = { "webostv.button", "", "{\"button\": \"ENTER\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_13 = {.haservice = action_data_member_13 };
const struct action action_13 = { action_data_13, ACTION_HASERVICE };
const struct action actions_13[] = { action_13, };
const struct button button_13 = { "TV Input Enter", "placeholder", &placeholder_bmp, "Enter", 1, actions_13 };
const struct action_haservice action_data_member_14 = { "webostv.button", "", "{\"button\": \"HOME\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_14 = {.haservice = action_data_member_14 };
const struct action action_14 = { action_data_14, ACTION_HASERVICE };
const struct action actions_14[] = { action_14, };
const struct button button_14 = { "TV Input AppMenu", "placeholder", &placeholder_bmp, "App Menu", 1, actions_14 };
const struct action_haservice action_data_member_15 = { "webostv.button", "", "{\"button\": \"BACK\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_15 = {.haservice = action_data_member_15 };
const struct action action_15 = { action_data_15, ACTION_HASERVICE };
const struct action actions_15[] = { action_15, };
const struct button button_15 = { "TV Input Back", "placeholder", &placeholder_bmp, "Back", 1, actions_15 };
const struct action_haservice action_data_member_16 = { "webostv.button", "", "{\"button\": \"EXIT\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_16 = {.haservice = action_data_member_16 };
const struct action action_16 = { action_data_16, ACTION_HASERVICE };
const struct action actions_16[] = { action_16, };
const struct button button_16 = { "TV Input Exit", "placeholder", &placeholder_bmp, "Exit", 1, actions_16 };
const struct action_native action_data_member_17 = { "redraw", "" };
const union actionData action_data_17 = {.native = action_data_member_17 };
const struct action action_17 = { action_data_17, ACTION_NATIVE };
const struct action actions_17[] = { action_17, };
const struct button button_17 = { "Refresh Display", "placeholder", &placeholder_bmp, "Redraw", 1, actions_17 };
const struct action_haservice action_data_member_18 = { "webostv.button", "", "{\"button\": \"POWER\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_18 = {.haservice = action_data_member_18 };
const struct action action_18 = { action_data_18, ACTION_HASERVICE };
const struct action actions_18[] = { action_18, };
const struct button button_18 = { "TV Power Toggle", "placeholder", &placeholder_bmp, "Power", 1, actions_18 };
const struct action_haservice action_data_member_19 = { "webostv.button", "", "{\"button\": \"MENU\", \"entity_id\": \"media_player.livingroom_tv\"}" };
const union actionData action_data_19 = {.haservice = action_data_member_19 };
const struct action action_19 = { action_data_19, ACTION_HASERVICE };
const struct action actions_19[] = { action_19, };
const struct button button_19 = { "TV Menu", "placeholder", &placeholder_bmp, "Menu", 1, actions_19 };
const struct action_native action_data_member_20 = { "light_select", "light.livingroom_all_lights" };
const union actionData action_data_20 = {.native = action_data_member_20 };
const struct action action_20 = { action_data_20, ACTION_NATIVE };
const struct action actions_20[] = { action_20, };
const struct button button_20 = { "Livingroom Lights", "placeholder", &placeholder_bmp, "Livingroom", 1, actions_20 };
const struct action_native action_data_member_21 = { "light_select", "light.kitchen_and_dining_room_all_lights" };
const union actionData action_data_21 = {.native = action_data_member_21 };
const struct action action_21 = { action_data_21, ACTION_NATIVE };
const struct action actions_21[] = { action_21, };
const struct button button_21 = { "Kitchen Lights", "placeholder", &placeholder_bmp, "Kitchen", 1, actions_21 };
const struct action_native action_data_member_22 = { "light_select", "light.master_bedroom_all_lights" };
const union actionData action_data_22 = {.native = action_data_member_22 };
const struct action action_22 = { action_data_22, ACTION_NATIVE };
const struct action actions_22[] = { action_22, };
const struct button button_22 = { "Master Bedroom Lights", "placeholder", &placeholder_bmp, "Mstr Bdrm", 1, actions_22 };
const struct action_native action_data_member_23 = { "light_select", "light.outside_lights" };
const union actionData action_data_23 = {.native = action_data_member_23 };
const struct action action_23 = { action_data_23, ACTION_NATIVE };
const struct action actions_23[] = { action_23, };
const struct button button_23 = { "Outside Lights", "placeholder", &placeholder_bmp, "Outside", 1, actions_23 };
const struct action_native action_data_member_24 = { "light_off", "" };
const union actionData action_data_24 = {.native = action_data_member_24 };
const struct action action_24 = { action_data_24, ACTION_NATIVE };
const struct action actions_24[] = { action_24, };
const struct button button_24 = { "Lights Off", "placeholder", &placeholder_bmp, "Turn Off", 1, actions_24 };
const struct action_native action_data_member_25 = { "light_on", "" };
const union actionData action_data_25 = {.native = action_data_member_25 };
const struct action action_25 = { action_data_25, ACTION_NATIVE };
const struct action actions_25[] = { action_25, };
const struct button button_25 = { "Lights On", "placeholder", &placeholder_bmp, "Turn On", 1, actions_25 };
const struct action_native action_data_member_26 = { "light_green_up", "" };
const union actionData action_data_26 = {.native = action_data_member_26 };
const struct action action_26 = { action_data_26, ACTION_NATIVE };
const struct action actions_26[] = { action_26, };
const struct button button_26 = { "Lights Green Up", "placeholder", &placeholder_bmp, "Green +", 1, actions_26 };
const struct action_native action_data_member_27 = { "light_green_down", "" };
const union actionData action_data_27 = {.native = action_data_member_27 };
const struct action action_27 = { action_data_27, ACTION_NATIVE };
const struct action actions_27[] = { action_27, };
const struct button button_27 = { "Lights Green Down", "placeholder", &placeholder_bmp, "Green -", 1, actions_27 };
const struct action_native action_data_member_28 = { "light_red_up", "" };
const union actionData action_data_28 = {.native = action_data_member_28 };
const struct action action_28 = { action_data_28, ACTION_NATIVE };
const struct action actions_28[] = { action_28, };
const struct button button_28 = { "Lights Red Up", "placeholder", &placeholder_bmp, "Red +", 1, actions_28 };
const struct action_native action_data_member_29 = { "light_red_down", "" };
const union actionData action_data_29 = {.native = action_data_member_29 };
const struct action action_29 = { action_data_29, ACTION_NATIVE };
const struct action actions_29[] = { action_29, };
const struct button button_29 = { "Lights Red Down", "placeholder", &placeholder_bmp, "Red -", 1, actions_29 };
const struct action_native action_data_member_30 = { "light_blue_up", "" };
const union actionData action_data_30 = {.native = action_data_member_30 };
const struct action action_30 = { action_data_30, ACTION_NATIVE };
const struct action actions_30[] = { action_30, };
const struct button button_30 = { "Lights Blue Up", "placeholder", &placeholder_bmp, "Blue +", 1, actions_30 };
const struct action_native action_data_member_31 = { "light_blue_down", "" };
const union actionData action_data_31 = {.native = action_data_member_31 };
const struct action action_31 = { action_data_31, ACTION_NATIVE };
const struct action actions_31[] = { action_31, };
const struct button button_31 = { "Lights Blue Down", "placeholder", &placeholder_bmp, "Blue -", 1, actions_31 };
const struct action_native action_data_member_32 = { "light_white_up", "" };
const union actionData action_data_32 = {.native = action_data_member_32 };
const struct action action_32 = { action_data_32, ACTION_NATIVE };
const struct action actions_32[] = { action_32, };
const struct button button_32 = { "Lights White Up", "placeholder", &placeholder_bmp, "White +", 1, actions_32 };
const struct action_native action_data_member_33 = { "light_white_down", "" };
const union actionData action_data_33 = {.native = action_data_member_33 };
const struct action action_33 = { action_data_33, ACTION_NATIVE };
const struct action actions_33[] = { action_33, };
const struct button button_33 = { "Lights White Down", "placeholder", &placeholder_bmp, "White -", 1, actions_33 };
const struct action_native action_data_member_34 = { "light_brightness_up", "" };
const union actionData action_data_34 = {.native = action_data_member_34 };
const struct action action_34 = { action_data_34, ACTION_NATIVE };
const struct action actions_34[] = { action_34, };
const struct button button_34 = { "Lights Brightness Up", "placeholder", &placeholder_bmp, "Brightness +", 1, actions_34 };
const struct action_native action_data_member_35 = { "light_brightness_down", "" };
const union actionData action_data_35 = {.native = action_data_member_35 };
const struct action action_35 = { action_data_35, ACTION_NATIVE };
const struct action actions_35[] = { action_35, };
const struct button button_35 = { "Lights Brightness Down", "placeholder", &placeholder_bmp, "Brightness -", 1, actions_35 };
const struct action_jump action_data_member_36 = { "Lights" };
const union actionData action_data_36 = {.jump = action_data_member_36 };
const struct action action_36 = { action_data_36, ACTION_JUMP };
const struct action actions_36[] = { action_36, };
const struct button button_36 = { "Control Lights", "placeholder", &placeholder_bmp, "Lights", 1, actions_36 };
const struct action_jump action_data_member_37 = { "TV" };
const union actionData action_data_37 = {.jump = action_data_member_37 };
const struct action action_37 = { action_data_37, ACTION_JUMP };
const struct action actions_37[] = { action_37, };
const struct button button_37 = { "Control TV", "placeholder", &placeholder_bmp, "TV", 1, actions_37 };
struct button buttons[] = { button_0,button_1,button_2,button_3,button_4,button_5,button_6,button_7,button_8,button_9,button_10,button_11,button_12,button_13,button_14,button_15,button_16,button_17,button_18,button_19,button_20,button_21,button_22,button_23,button_24,button_25,button_26,button_27,button_28,button_29,button_30,button_31,button_32,button_33,button_34,button_35,button_36,button_37, };
uint32_t numButtons = 38;
